config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :friendships, only: %i[create destroy]
  resources :reactions, only: %i[create destroy]
  resources :users, only: %i[show notifications index friends] do
    member do
      get :friends
      get :notifications
      resources :profiles, only: %i[new create edit update]
    end
  end
  resources :posts, only: %i[create destroy show edit update index] do
    resources :comments, only: %i[create destroy edit]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :comments, foreign_key: :parent_id, dependent: :destroy
  has_many :reactions, as: :reactable, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }

  def message
    if parent.nil?
      'commented on your post'
    else
      "replied to your comment: #{parent.content.truncate(85)}"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :log_in_user
  before_action :set_post, only: %i[create destroy]

  def create
    @comment = @post.comments.create(comment_params)
    if @comment.save
      notify(@post.user, @comment)
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.turbo_stream
      end
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post), status: :see_other }
      format.turbo_stream
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :parent_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def notify(user, comment)
    user = comment.parent.user unless comment.parent.nil?
    return if current_user == user

    user.notifications.create(notifiable: comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment.persisted? %>
  <div id=<%= "comment#{comment.id}" %> class=<%="pt-3"%> >

    <% unless comment.parent.nil? %>
      <div class='block md:hidden flex items-center gap-1 text-gray-600 dark:text-gray-400 mb-3 ml-[9.2px] text-xs'>
        <div class="flex items-center gap-2">
          <img src=<%= profile_img(comment.parent.user) %> 
                class="rounded-full w-5 h-5">

          <p class='font-bold'><%= "#{comment.parent.user.username}:"  %></p>
        </div>
        <p><%= comment.parent.content.truncate(40) %><p>
      </div>
    <% end %>

    <div class='flex items-center justify-between'>
      <div class="flex items-center gap-3">
        <img src=<%= profile_img(comment.user) %> 
              class="rounded-full w-10 h-10">

        <p class='font-bold'><%= link_to comment.user.username, comment.user %></p>
      </div>

      <p class="text-xs text-gray-800 dark:text-gray-200 justify-self-end"><%= time_ago_in_words(comment.created_at) %> ago</p>
    </div>

    <p class='mt-2 mb-4 break-words'><%= comment.content%></p>

    <div class="flex justify-between items-center">
          <div class="flex gap-x-3">
              <div class="flex justify-center gap-x-1">
                  <span id=<%= "comment_reaction_count#{comment.id}" %> ><%= comment.reactions.count %></span>
                  <%= render 'reactions/reaction_form',  :@reactable => comment %>
              </div>
          </div>

          <div class="flex gap-x-3">
              <ion-icon id=<%="reply-btn#{comment.id}"%> class='reply-btn hover:cursor-pointer text-xl' name="arrow-undo" data-controller="reply-form" data-action="click->reply-form#toggle"></ion-icon>

              <% if current_user == comment.user %>
                  <%= button_to  post_comment_path(@post, comment), method: :delete do %>
                    <ion-icon id=<%="trash#{comment.id}"%> class="text-xl" name="trash-outline"></ion-icon>
                  <% end %>
              <% end %>
          </div>
    </div>

    <div class='reply-form hidden' data-action="reply-form#toggle">
      <%= render 'comments/comment_form', :parent => comment %>
    </div>

    <hr class="h-[1px] border-none bg-gray-300 dark:bg-gray-700 my-[0px]">
    
    <div id=<%= "nested#{comment.id}" %> class='pl-0 md:pl-7'>
      <%= render comment.comments %>
    </div>
  </div>
<% end %>

app/views/comments/_comment_form.html.erb
<div class="bg-white shadow-md dark:bg-dm-2 dark:shadow-none rounded-[6px] duration-500 mb-4 py-3 px-4 border border-gray-100 dark:border-gray-700">
   <%= form_with model: [ @post, @post.comments.build ], data: { controller: 'forms', action: "turbo:submit-end->forms#clear" } do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :parent_id, :value => parent.id unless parent.nil? %>
      <%= f.text_area :content, placeholder: "Write a comment here:", :class => 'input-primary dark:input-dark resize-none my-3 h-14 shadow-none outline-none p-0 my-0' %>
      <div class='flex justify-end mt-2'>
         <span data-controller="reply-form" data-action="click->reply-form#close"><%= f.submit "Post", :class => 'bg-emerald-500 hover:bg-emerald-400 dark:bg-emerald-600 dark:hover:bg-emerald-500s text-white px-3 py-2 rounded-md duration-500 hover:cursor-pointer' %></span>
      </div>
   <% end %>
</div>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update "comment_count#{@comment.post.id}" do %>
  <%= pluralize(@post.comments.count, 'Comment') %>
<% end %>

<% if @comment.parent.nil? %>
  <%= turbo_stream.append "comments#{@comment.post.id}" do %>
    <%= render @comment %>
  <% end %>
<% else %>
  <%= turbo_stream.append "nested#{@comment.parent.id}" do %>
    <%= render @comment %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.update "comment_count#{@comment.post.id}" do %>
  <%= pluralize(@post.comments.count, 'Comment') %>
<% end %>

<%= turbo_stream.remove "comment#{@comment.id}" %>