config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :friendships, only: %i[create destroy]
  resources :reactions, only: %i[create destroy]
  resources :users, only: %i[show notifications index friends] do
    member do
      get :friends
      get :notifications
      resources :profiles, only: %i[new create edit update]
    end
  end
  resources :posts, only: %i[create destroy show edit update index] do
    resources :comments, only: %i[create destroy edit]
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  has_many :notifications, as: :notifiable, dependent: :destroy

  validates :user_id, presence: true
  validates :friend_id, presence: true

  def message
    if friend.recived_request?(user)
      'sent you a friend request'
    elsif initial_request?
      "'s friend request was accepted"
    else
      'accepted your friend request'
    end
  end

  def initial_request?
    return unless user.friends_with?(friend)

    other_friendship = friend.friendships.find_by(friend_id: user_id)
    created_at < other_friendship.created_at
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :log_in_user

  def create
    @user = User.find(params[:friend_id])
    current_user.add_friend(@user)
    friendship = current_user.friendships.find_by(friend: @user)
    notify(@user, friendship)
    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.turbo_stream
    end
  end

  def destroy
    friendship = Friendship.find(params[:id])
    @friend = select_friend(friendship)
    current_user.unfriend(@friend)
    respond_to do |format|
      format.html { redirect_to request.referrer, status: :see_other }
      format.turbo_stream
    end
  end

  private

  def select_friend(friendship)
    if friendship.friend == current_user
      friendship.user
    else
      friendship.friend
    end
  end

  def notify(user, friendship)
    user.notifications.create(notifiable: friendship)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/create.turbo_stream.erb
<%= turbo_stream.update "friend_form#{@user.id}" do %>
  <% if params[:page] == "users#notifications" %>
    <%= nil %>
  <% else %>
    <%= render "users/unfriend", :user => @user  %>
  <% end %>
<% end %>

<%= turbo_stream.update "friend_count#{@user.id}" do %>
  <%= link_to pluralize(@user.active_friends.count, 'friend'), friends_user_path(@user) %>
<% end %>

<%= turbo_stream.update "friendship-message#{@user.id}" do %>
  <% if current_user.friends_with?(@user) %>
    <%= @user.friendships.find_by(friend: current_user).message %>
  <% end %>
<% end %>

app/views/friendships/destroy.turbo_stream.erb
<%= turbo_stream.update "friend_form#{@friend.id}" do %>
  <%= render "users/add_friend", :user => @friend %>
<% end %>

<%= turbo_stream.update "friend_count#{@friend.id}" do %>
  <%= link_to pluralize(@friend.active_friends.count, 'friend'), friends_user_path(@friend) %>
<% end %>

<%= turbo_stream.remove "friendship#{@friend.id}" %>