config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :friendships, only: %i[create destroy]
  resources :reactions, only: %i[create destroy]
  resources :users, only: %i[show notifications index friends] do
    member do
      get :friends
      get :notifications
      resources :profiles, only: %i[new create edit update]
    end
  end
  resources :posts, only: %i[create destroy show edit update index] do
    resources :comments, only: %i[create destroy edit]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :reactions, as: :reactable, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image do |attachable|
    attachable.variant :display, resize_to_limit: [500, 500]
  end

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: 'must be a valid image format' },
                      size: { less_than: 5.megabytes,
                              message: 'should be less than 5MB' }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[destroy edit update show correct_user]
  before_action :correct_user, only: %i[destroy edit update]
  before_action :log_in_user

  def index
    return unless user_signed_in?

    @post = current_user.posts.build
    @feed = current_user.feed.page(params[:page])
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.image.attach(params[:post][:image])
    if @post.save
      redirect_to request.referrer
    else
      @feed = current_user.feed.page(params[:page])
      render 'index', status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_url, status: :see_other
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      redirect_to request.referrer, status: :see_other
    end
  end

  def show; end

  def edit; end

  private

  def post_params
    params.require(:post).permit(:content, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def correct_user
    redirect_to root_url, status: :see_other unless @post.user == current_user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index_post.html.erb
<div class=" flex flex-col bg-white shadow-md dark:bg-dm-2 dark:shadow-none rounded-[6px] duration-500 mt-3 mb-8 py-3 px-4 border border-gray-100 dark:border-gray-700">
    <div class="flex items-center justify-between">
        <div class="flex items-center gap-3 ">
            <img src=<%= profile_img(post.user) %> 
                class="rounded-full w-11 h-11">

            <p class="font-bold"><%= link_to post.user.username, post.user %></p>
        </div>

        <p class="text-xs text-gray-800 dark:text-gray-200 justify-self-end"><%= time_ago_in_words(post.created_at) %> ago</p>
    </div>

    <p class="text-gray-800 dark:text-gray-200 my-3 break-words"><%= post.content %><p>

    <div class='self-center mb-2'>
        <%= image_tag post.image.variant(:display), class: 'rounded-md' if post.image.attached? %>
    </div>

    <div class="flex justify-between items-center mt-3">
        <div class="flex gap-x-3">
            <div class="flex justify-center gap-x-1">
                <span id=<%= "post_reaction_count#{post.id}" %> ><%= post.reactions.count %></span>
                <span><%= render 'reactions/reaction_form',  :@reactable => post %></span>
            </div>

            <%= link_to post_path(post) do %>
              <span><%= post.comments.count %></span>
              <ion-icon class="text-xl" name="chatbubbles-outline"></ion-icon>
            <% end %>
        </div>

         <div class="flex gap-x-3">
            <% if current_user == post.user %>
                <%= link_to edit_post_path(post) do %>
                  <ion-icon class="edit text-xl" name="create-outline"></ion-icon>
                <% end %>
                <%= button_to post, method: :delete do %>
                  <ion-icon class="trash text-xl" name="trash-outline"></ion-icon>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/_post.html.erb
<div>
  <div class=" flex flex-col bg-white shadow-md dark:bg-dm-2 dark:shadow-none rounded-[6px] duration-500 my-3 py-3 px-4 border border-gray-100 dark:border-gray-700">
    <div class="flex items-center justify-between">
      <div class="flex items-center gap-3 ">
      
        <img src=<%= profile_img(post.user) %> 
          class="rounded-full w-10 h-10 md:w-14 md:h-14">

        <strong><%= link_to post.user.username, post.user %></strong>
      </div>
      <p class="text-xs text-gray-800 dark:text-gray-200 justify-self-end"><%= time_ago_in_words(post.created_at) %> ago</p>
    </div>

   <p class="text-gray-800 dark:text-gray-200 my-3 break-words"><%= post.content %><p>

    <div class='self-center mb-2'>
      <%= image_tag post.image.variant(:display), class: 'rounded-md' if post.image.attached? %>
    </div>

    <div class="flex justify-between items-center">
        <div class="flex gap-x-3">
            <div class="flex justify-center gap-x-1">
                <span id=<%= "post_reaction_count#{post.id}" %> ><%= post.reactions.count %></span>
                <span><%= render 'reactions/reaction_form',  :@reactable => post %></span>
            </div>
        </div>

         <div class="flex gap-x-3">
            <% if current_user == post.user %>
                <%= link_to edit_post_path(post) do %>
                  <ion-icon id=<%="edit#{post.id}"%> class="edit text-xl" name="create-outline"></ion-icon>
                <% end %>
                <%= button_to post, method: :delete do %>
                  <ion-icon id=<%="trash#{post.id}"%> class="trash text-xl" name="trash-outline"></ion-icon>
                <% end %>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post_form.html.erb
<%= render 'layouts/error_messages', object: @post %>

<div class="bg-white shadow-md dark:bg-dm-2 dark:shadow-none rounded-[6px] duration-500 mt-2 mb-8 py-3 px-4 border border-gray-100 dark:border-gray-700">
  <%= form_with(model: @post) do |f| %>
    <%= f.text_area :content, placeholder: "Write your new post here...", :class => 'input-primary dark:input-dark resize-none my-3 h-28 shadow-none outline-none p-0 my-0' %>
    <div class="flex justify-between items-center">
      <span class="image mt-4">
          <%= f.label :image do %>
            <ion-icon name="image-outline" class="z-[-1] text-3xl hover:cursor-pointer"></ion-icon>
          <% end %>
          <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png", :class => 'inputfile' %>
      </span>
      <%= f.submit "Post", :class => 'bg-emerald-500 hover:bg-emerald-400 dark:bg-emerald-600 dark:hover:bg-emerald-500 text-white px-3 py-2 rounded-md duration-500 hover:cursor-pointer'%>
    </div>
  <% end %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.update "feed#{@post.user.id}" do %>
  <%= render @post.user.feed %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.update "feed#{@post.user.id}" do %>
  <%= render @post.user.feed %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'posts/post_form' %>

app/views/posts/index.html.erb
<%= turbo_frame_tag "post-index" do %>
  <div>
    <h1 class="text-3xl duration-500 font-bold">Welcome <%= current_user.username %></h1>
      
    <%= render 'posts/post_form' %>

    <% unless @feed.empty? %>
    <div id=<%= "feed#{current_user.id}"%> >
      <% @feed.each do |post| %>
        <%= render 'index_post', :post => post %>
      <% end %>
      <%= paginate @feed %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render @post %>

<h2 id=<%= "comment_count#{@post.id}" %> class='text-3xl duration-500 font-bold my-4'><%= pluralize(@post.comments.count, 'Comment') %></h2>
<%= render 'comments/comment_form', :parent => nil %>

<div id=<%= "comments#{@post.id}" %>>
  <%= render @post.comments.where(parent_id: nil) %>
</div>