config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :friendships, only: %i[create destroy]
  resources :reactions, only: %i[create destroy]
  resources :users, only: %i[show notifications index friends] do
    member do
      get :friends
      get :notifications
      resources :profiles, only: %i[new create edit update]
    end
  end
  resources :posts, only: %i[create destroy show edit update index] do
    resources :comments, only: %i[create destroy edit]
  end
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger text-red-600">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="text-red-600"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<div class="flex justify-center">
    <% unless notice.nil? %>
        <p class="notice bg-emerald-500 text-center text-white border-solid rounded-md w-fit m-auto py-2 px-3 my-3"><%= notice %></p>
    <% end %>

    <% unless alert.nil? %>
        <p class="alert bg-red-500 text-center text-white border-solid rounded-md w-fit m-auto py-2 px-3 my-3"><%= alert %></p>
    <% end %>

    <%# <p id="reply-alert" class="alert text-center text-white bg-red-500 rounded-md w-fit m-auto py-2 px-3 my-3 fixed z-10 hidden"></p> %>
    <%# <p id="reply-notice" class="duration-500 alert text-center text-white bg-emerald-500 dark:bg-emerald-600 rounded-md w-fit m-auto py-2 px-3 my-3 fixed z-10 hidden"></p> %>
</div>

app/views/layouts/_nav.html.erb
<% if current_user %>
    <nav id="nav" class="pt-2 px-4 md:flex md:flex-col fixed md:h-screen md:w-fit w-full z-50 ">
        <div class="flex justify-between items-center">
            <span>
                <%= link_to root_path do %>
                  <ion-icon name="diamond-sharp" class="hidden md:block text-4xl md:mx-7 my-3 <%= text_colors[current_user.profile.color.to_sym] %>"></ion-icon>
                <% end %>
            </span>

            <span class="text-3xl cursor-pointer mx-2 md:hidden block">
                <ion-icon id="burger" class="p-2 bg-lm-1 dark:bg-dm-1 rounded-full shadow-md dark:shadow-gray-800" name="menu"></ion-icon>
            </span>
        </div>

        <ul id="list" class="md:flex flex-col md:ml-4 md:static absolute w-full h-screen left-0 md:w-auto md:py-0 py-4 md:pl-0 pl-0 mt-0 bg-lm-1 dark:bg-dm-1 z-50">
            <%= link_to root_path do %>
                <li class="nav-item mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 w-fit py-2 px-3 rounded-3xl duration-500 flex items-center gap-3">
                    <ion-icon name="home" class="text-2xl"></ion-icon>
                     <p>Home</p>
                </li>
            <% end %>

            <%= link_to current_user do %>
                <li class="nav-item mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 w-fit py-2 px-3 rounded-3xl duration-500 flex items-center gap-3">
                    <ion-icon name="person-circle" class="text-2xl"></ion-icon>
                    <p>Profile</p>
                </li>
            <% end %>

             <%= link_to notifications_user_path(current_user) do %>
                <li class="nav-item mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 w-fit py-2 px-3 rounded-3xl duration-500 flex items-center gap-3">
                    <% unless current_user.new_notifications.count.zero? %>
                    <span class="text-sm bg-rose-500 w-[9px] h-[9px] rounded-full absolute z-[1] ml-[15px] mb-3 text-rose-500 border border-lm-1 dark:border-dm-1"></span>
                    <% end %>
                    <ion-icon name="notifications" class="text-2xl"></ion-icon>
                    <p>Notifications</p>
                </li>
            <% end %>

            <%= link_to users_path do %>
                <li class="nav-item mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 w-fit py-2 px-3 rounded-3xl duration-500 flex items-center gap-3">
                    <ion-icon name="accessibility" class="text-2xl"></ion-icon>
                    <p>Find friends</p>
                </li>
            <% end %>

            <%= link_to edit_user_registration_path do %>
                <li class="nav-item mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 w-fit py-2 px-3 rounded-3xl duration-500 flex items-center gap-3">
                    <ion-icon name="cog" class="text-2xl"></ion-icon>
                    <p>Settings</p>
                </li>
            <% end %>

             <%= link_to destroy_user_session_path, data: { turbo_method: :delete } do %>
                <li class="nav-item mx-1 my-3 text-xl hover:bg-gray-200 dark:hover:bg-gray-800 w-fit py-2 px-3 rounded-3xl duration-500 flex items-center gap-3">
                    <ion-icon name="log-out" class="text-2xl"></ion-icon>
                     <p>Log out</p>
                </li>
            <% end %>

            <li class="mx-1 my-3">
              <span class="text-2xl cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-800 w-fit duration-500 rounded-full flex justify-center items-center p-2">
                <ion-icon id="dark-mode" name="sunny-outline"></ion-icon>
              </span>
            </li>
        </ul>
    </nav>
<% end %>

app/views/layouts/_stats.html.erb
<div class="hidden lg:block flex flex-col mt-10 ml-7 mr-2">

  <div>
    <h3 class="text-3xl font-bold mb-2">New members</h3>

    <div class="flex flex-col gap-y-5 bg-white shadow-md dark:bg-dm-2 dark:shadow-none rounded-[6px] border border-gray-100 dark:border-gray-700 py-3 px-4 duration-500">
      <% @new_members.each do |m| %>
        <div class="flex items-center">
            <img src=<%= profile_img(m) %> class="rounded-full w-14 h-14 mr-3">
            <p class="underline"><%= link_to m.username, m %></p>
        </div>
      <% end %> 
    </div>
  </div>

  <div class="mt-7">
    <h3 class="text-3xl font-bold mb-2">Latest posts</h3>

    <div class="flex flex-col gap-y-4 bg-white shadow-md dark:bg-dm-2 dark:shadow-none rounded-[6px] border border-gray-100 dark:border-gray-700 py-3 px-4 duration-500">
      <% @latest_posts.each do |p| %>
        <div class="flex items-center">
          <img src=<%= profile_img(p.user) %> class="rounded-full w-10 h-10 mr-3">
          <p><%= link_to p.user.username, p.user %></p>
        </div>

        <div>
          <%= link_to p do %>
            <p class='text-gray-600 dark:text-gray-400 break-words'><%= p.content.truncate(95) %></p>
            <hr class="h-[1px] border-none bg-gray-200 dark:bg-gray-800 my-[5px]">
        <% end %>
      </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="poppins">
  <head>
    <title>Gemz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </head>

  <body class='poppins bg-lm-1 text-dm-1 dark:bg-dm-1 dark:text-lm-1 h-screen w-screen' > 
    <%= render 'layouts/nav' %>
    <div class="w-full <%= main_layout %>">
      <div class="w-full <%= right_content %>">
        <%= render 'layouts/flash' %>
        <div class='<%= grid_layout("#{controller_name}##{action_name}") %>'>
          <%= yield %>
          <%= render 'layouts/stats' if include_stats?("#{controller_name}##{action_name}") %>
        </div>
      </div>
    </div>
  </body>
</html>